repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: spotinst
    url: https://spotinst.github.io/spotinst-kubernetes-helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: datadog
    url: https://helm.datadoghq.com

releases:
  - name: external-dns
    namespace: kube-system
    chart: bitnami/external-dns
    version: ^2.0.0
    values:
      - helm_values/external-dns.yaml.gotmpl

  - name: datadog
    namespace: kube-system
    chart: datadog/datadog
    version: ~2.4.35
    values:
      - helm_values/datadog.yaml.gotmpl

  - name: spotinst-kubernetes-cluster-controller
    namespace: kube-system
    chart: spotinst/spotinst-kubernetes-cluster-controller
    version: ^1.0.54
    values:
      - helm_values/spotinst.yaml.gotmpl

  - name: metrics-server
    namespace: kube-system
    chart: stable/metrics-server
    version: ~2.11.2
    values:
      - helm_values/metrics-server.yaml

  - name: kube-state-metrics
    namespace: kube-system
    chart: stable/kube-state-metrics
    version: ~2.9.2

  - name: cloudhealth
    namespace: default
    chart: ../../../../charts/cloudhealth
    values:
      - ../../common/helm_values/cloudhealth.yaml
      - cloudhealth:
          clusterName: infra-prod-usw2-a

environments:
  default:
    values:
      - cluster.yaml
    secrets:
      - secrets.yaml
