name: "helmfile lock stale"
description: "A composite action to check if the helmfile lock is missing or stale"
inputs:
  working_directory:
    description: "The directory to run the action in"
    required: false
    default: "."
  days_stale:
    description: "Threshold for determining if a helmfile lock is stale or not"
    required: false
    default: 30
outputs:
  helmfile-lock-state:
    description: "State of the helmfile lock. i.e. missing, stale, fresh"
    value: ${{ steps.main.outputs.helmfile-lock-state }}
  helmfile-lock-staleness-delta-approx:
    description: "How many days stale is the lock approximately"
    value: ${{ steps.main.outputs.helmfile-lock-staleness-delta-approx }}
runs:
  using: "composite"
  steps:
    - name: "staleness check"
      shell: bash
      id: main
      working-directory: ${{ inputs.working_directory }}
      run: ${{ github.action_path }}/main.sh "${{ inputs.working_directory }}" "${{ days_stale }}"
