name: "helmfile action"
description: "A composite action wrapper around helmfile"
inputs:
  command:
    description: "The helmfile command to run"
    required: true
  working_directory:
    description: "The directory to run all the commands in"
    required: false
    default: "."
outputs: {}
runs:
  using: "composite"
  steps:
    - name: helmfile
      shell: bash
      id: main
      working-directory: ${{ inputs.working_directory }}
      run: ${{ github.action_path }}/main.sh "${{ inputs.command }}" "${{ inputs.working_directory }}"
