name: "build-workspace-matrix"
description: "Builds a matrix of workspaces based on glob patterns and analysis of which files have changed"
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    required: true
  workspaces:
    description: "A newline-separated list of globs or dependency glob expressions ('workspace-glob : dependency-glob') representing specific workspaces"
    required: true
  workflow_dispatch_workspace:
    description: "A particular workspace to return when the event type is 'workflow_dispatch'"
    required: false
  global_dependencies:
    description: "A newline-separated list of globs representing dependencies of each workspace. If any of the dependencies have changed then all workspaces will be returned. Applies only to 'push' and 'pull_request' events."
    required: false
  relative_to_path:
    description: "If provided, results will be relative to the given path"
    required: false
  working_directory:
    description: "If provided, the action uses the specified path as the root for the purposes of detecting matching workspaces based on the provided glob patterns."
    required: false
outputs:
  matrix:
    description: "The matrix object of the shape: { workspace: [] }"
runs:
  using: "node20"
  main: "dist/index.js"
