name: Find Path Owners
author: iStreamPlanet
description: Finds owners of a given path based on the GitHub CODEOWNERS file
inputs:
  path:
    description: The path to match against the CODEOWNERS file
    required: true
outputs:
  owners:
    description: A JSON-encoded array of matched owners
runs:
  using: 'node16'
  main: 'dist/index.js'