name: Deploy

on:
  workflow_call:
    inputs:
      app-region:
        description: "Application region, ie US_WEST or US_EAST"
        required: false
        type: string
      atomic:
        description: "Deploy to atomic clusters"
        required: false
        type: boolean
        default: false
      awsAccount:
        description: "AWS Account ID"
        required: false
        type: string
      release:
        description: "Helm release name"
        required: true
        type: string
      clusters:
        description: "JSON array of cluster configs"
        required: true
        type: string
      chart-name:
        description: "Chart name (used in chart-path)"
        required: true
        type: string
      chart-path:
        description: "Path to Helm chart"
        required: true
        type: string
      chart-version:
        description: "Version tag for the chart"
        required: true
        type: string
      config-files:
        description: "Additional config files"
        required: false
        type: string
      deployregion:
        description: "Deploy region, ie US_WEST or US_EAST"
        required: false
        type: string
      helm-repo-usw2:
        description: "Helm repo URL for US_WEST_2"
        required: false
        type: string
      helm-repo-use1:
        description: "Helm repo URL for US_EAST_1"
        required: false
        type: string
      helm-s3-plugin-version:
        description: "Helm S3 plugin version"
        required: false
        type: string
      plugins:
        description: "Helm plugin URL"
        required: false
        default: "https://github.com/hypnoglow/helm-s3.git"
        type: string
      value-files:
        description: "YAML files to pass to helm as -f args"
        required: false
        type: string

    secrets:
      CLUSTER_AWS_ACCESS_KEY_ID:
        required: true
      CLUSTER_AWS_SECRET_ACCESS_KEY:
        required: true
      CDS_USER:
        required: false
      CDS_KEY:
        required: false
      MC_LICENSE:
        required: false

jobs:
  deploy:
    name: Deploy Helm chart for release ${{ inputs.release }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
    strategy:
      matrix:
        cluster: ${{ fromJson(inputs.clusters) }}
      max-parallel: 1
    steps:
      - name: Configure AWS credentials (${{ matrix.cluster.region }})
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CLUSTER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CLUSTER_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ matrix.cluster.region }}
          role-to-assume: ${{ matrix.cluster.role-arn }}

      - name: Dry-run Helm to ${{ matrix.cluster.name }}
        uses: lmorris-isp/github-actions-deploy-eks-helm@main
        with:
          aws-region: ${{ matrix.cluster.region }}
          chart-repository: ${{ matrix.cluster.helm-s3-repo }}
          chart-path: ${{ matrix.cluster.name }}/${{ inputs.chart-name }}
          version: ${{ inputs.chart-version }}
          cluster-name: ${{ matrix.cluster.name }}
          namespace: ${{ matrix.cluster.namespace }}
          name: ${{ inputs.release }}
          plugins: ${{ inputs.plugins }}
          helm-s3-plugin-version: ${{ inputs.helm-s3-plugin-version }}
          dry-run: true
          values: environment=${{ matrix.cluster.environment }},imageTag=${{ inputs.chart-version }},imageRegion=${{ matrix.cluster.region }},replicas=1

      - name: Deploy Helm to ${{ matrix.cluster.name }}
        uses: lmorris-isp/github-actions-deploy-eks-helm@main
        with:
          aws-region: ${{ matrix.cluster.region }}
          chart-repository: ${{ matrix.cluster.helm-s3-repo }}
          chart-path: ${{ matrix.cluster.name }}/${{ inputs.chart-name }}
          version: ${{ inputs.chart-version }}
          cluster-name: ${{ matrix.cluster.name }}
          namespace: ${{ matrix.cluster.namespace }}
          name: ${{ inputs.release }}
          plugins: ${{ inputs.plugins }}
          helm-s3-plugin-version: ${{ inputs.helm-s3-plugin-version }}
          values: environment=${{ matrix.cluster.environment }},imageTag=${{ inputs.chart-version }},imageRegion=${{ matrix.cluster.region }},replicas=1
