# Simple failure notification reusable workflow
#
# Fast Follows
#
# * inputs we can override, eg workflow name, message, title, etc...
# * an org wide var with the slack webhook so no one has to specify it

name: Failure Notification
on:
  workflow_call:
    secrets:
      slack_webhook:
        required: true

jobs:
  send_notification:
    name: Send Failure Notification
    runs-on: ubuntu-latest
    env:
      CI_BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:

    - name: Debug
      env:
       AS_AN_ENV_VAR: ${{ secrets.slack_webhook }}
      run: |
        echo "Github Action ${{ github.workflow }} Failed"
        echo "on ${{ github.repository }} Repo"
        echo "Tell ${{ github.triggering_actor }}"
        echo -n "Secret ends with: "
        echo "${AS_AN_ENV_VAR}" | tail -c 4
        echo ${{ secrets.slack_webhook }} | tail -c 10
        
    - name: Send Slack
      uses: slackapi/slack-github-action@v1.27.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        payload: |
          {
            "text": "GH Action ${{ github.workflow}} Failed on ${{ github.repository }}. Tell ${{ github.triggering_actor }}",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Github Workflow ${{ github.workflow }} Failed on ${{ github.repository }}!"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "See ${{ env.CI_BUILD_URL }}"
                  }
                ]
              }
            ]
          }
  fail:
    name: Don't mask failure
    runs-on: ubuntu-latest
    steps:
    - run: exit 1
