name: Failure Notification
on:
  workflow_call:
    secrets:
      slack_webhook:
        required: true

jobs:
  send_notification:
    name: Send Failure Notification
    runs-on: ubuntu-latest
    steps:
    - name: Send Slack
      uses: slackapi/slack-github-action@v1.27.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        payload: |
          {
            "text": "Text that never shows up",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": ":scream:Github Action Failed!","emoji": true
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "Eat all humans!: ${{ env.CI_BUILD_URL }}"
                  }
                ]
              }
            ]
          }
