name: PR fmt and docs
on:
  workflow_call:
    inputs:
      terraform-root-path:
        required: false
        type: string
      module-path:
        required: false
        type: string
      module-update-recursive:
        default: false
        required: false
        type: boolean
      git-push:
        default: false
        required: false
        type: boolean

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: terraform fmt
        uses: dflook/terraform-fmt@v1.25.1

      - name: commit
        if: ${{ inputs.git-push }}
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: "Automated: terraform fmt"
          path: "${{ inputs.terraform-root-path }}"

  module_docs:
    runs-on: ubuntu-latest
    needs: [fmt]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: module terraform-docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: "${{ inputs.module-path }}"
          output-file: README.md
          output-method: inject
          recursive: ${{ inputs.module-update-recursive }}
          git-push: "${{ inputs.git-push }}"
          git-commit-message: "Automated: terraform-docs"
          git-push-user-name: "${{ github.actor }}"
          git-push-user-email: "${{ github.actor }}@users.noreply.github.com"
