name: Terraform docs

# This reusable workflow processes the specified terraform modules paths
# to generate module docs in the specified output file and optionally pushes
# the changes up to the PR.
on:
  workflow_call:
    inputs:
      git_push:
        description: "Toggles the option to push the module doc and module format updates"
        default: false
        required: false
        type: boolean
      recursive:
        description: "Toggles the option to generate module docs recursively"
        default: false
        required: false
        type: boolean
      output_file:
        description: "Name of the output file for the module docs"
        default: README.md
        required: false
        type: string
      output_method:
        description: "Method to be used for updating the module doc output file, valid options are 'inject', 'replace', and 'print'"
        default: inject
        required: false
        type: string
      workspaces:
        description: "A newline-separated list of globs or dependency glob expressions ('workspace-glob : dependency-glob') representing specific workspaces"
        required: true
        type: string
      global_dependencies:
        description: "A newline-separated list of globs representing dependencies of each workspace. If any of the dependencies have changed then all workspaces will be returned. Applies only to 'push' and 'pull_request' events."
        required: false
        type: string
      relative_to_path:
        description: "If provided, results will be relative to the given path"
        required: false
        type: string

jobs:
  determine-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-workspace-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: build-workspace-matrix
        uses: iStreamPlanet/github-actions/build-workspace-matrix@v1.13.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          workspaces: ${{ inputs.workspaces }}
          workflow_dispatch_workspace: ${{ github.event.inputs.workspace }}
          global_dependencies: ${{ inputs.global_dependencies }}
          relative_to_path: ${{ inputs.relative_to_path }}

  module_docs:
    needs: [determine-matrix, fmt]
    runs-on: ubuntu-latest
    if: needs.determine-matrix.outputs.matrix != '{"workspace":[]}'
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.determine-matrix.outputs.matrix) }}
    concurrency: terraform-${{ matrix.workspace }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: module terraform-docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: "${{ matrix.workspace }}"
          output-file: "${{ inputs.output_file }}"
          output-method: ${{ inputs.output_method }}
          recursive: ${{ inputs.recursive }}
          git-push: "${{ inputs.git_push }}"
          git-commit-message: "Automated: terraform-docs for ${{ matrix.workspace }}"
          git-push-user-name: "${{ github.actor }}"
          git-push-user-email: "${{ github.actor }}@users.noreply.github.com"
