name: Wait For Commit
on:
  workflow_call:
    inputs:
      caller_job:
        description: "Name of the job that calls this workflow"
        type: string
        required: true
      check_interval:
        description: "The amount of seconds to wait between checks, adjust depending on the expected time all the checks and related CI's will take."
        type: number
        required: false
        default: 10
      secret_name_prefix:
        description: "String to prepend to all secrets names in the array"
        type: string
        required: false
        default: ""
      secret_name_suffix:
        description: "String to append to all secrets names in the array"
        type: string
        required: false
        default: ""
      string_replace_rules:
        description: "JSON encoded dictionary of regex that will be applied for replacing characters in the new secret names array. The key is the regex, and value is the replacement."
        type: string
        required: false

    outputs:
      commit_owners:
        description: "Array of owners for the current commit based on the CODEOWNERS file and the updated files"
        value: ${{ jobs.get_commit_owners.outputs.commit_owners }}
      secret_names_array:
        description: "An array of strings containing the names of the secrets built from the name of the owners"
        value: ${{ jobs.get_commit_owners.outputs.secret_names_array }}
      status:
        description: "Overall status of the commit that triggered the workflow"
        value: ${{ jobs.wait_for_status_and_checks.outputs.status }}

jobs:
  wait_for_status_and_checks:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.status_and_checks.outputs.status }}
    steps:
      - name: 'Wait for status and checks'
        uses: "WyriHaximus/github-action-wait-for-status@v1.4.0"
        id: status_and_checks
        with:
          # This argument ensures that this job is ignored, otherwise this step will get stuck
          # waiting for itself to finish
          ignoreActions: "${{ inputs.caller_job }} / ${{ github.job }}"
          checkInterval: ${{ inputs.check_interval }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  get_commit_owners:
    runs-on: ubuntu-latest
    outputs:
      commit_owners: ${{ steps.commit_owners.outputs.owners }}
      secret_names_array: ${{ steps.secret_names.outputs.new_string_array }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get commit owners
        id: commit_owners
        uses: iStreamPlanet/github-actions/get-commit-owners@main

      - name: Get secret names
        id: secret_names
        uses: iStreamPlanet/github-actions/manipulate-string-array@main
        with:
          string_replace_rules: ${{ inputs.string_replace_rules }}
          string_array: ${{ steps.commit_owners.outputs.owners }}
          string_prefix: ${{ inputs.secret_name_prefix }}
          string_suffix: ${{ inputs.secret_name_suffix }}
